# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'k:\Grade3\美妆网站项目\local_features\feature_predictor.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_predictor(object):
    def setupUi(self, predictor):
        predictor.setObjectName("predictor")
        predictor.resize(1152, 807)
        self.label = QtWidgets.QLabel(predictor)
        self.label.setGeometry(QtCore.QRect(720, 350, 311, 311))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(predictor)
        self.label_2.setGeometry(QtCore.QRect(20, 520, 150, 61))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(predictor)
        self.label_3.setGeometry(QtCore.QRect(20, 610, 150, 61))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(predictor)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(predictor)
        self.label_5.setGeometry(QtCore.QRect(740, 50, 81, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(predictor)
        self.label_6.setGeometry(QtCore.QRect(890, 50, 81, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(predictor)
        self.label_7.setGeometry(QtCore.QRect(740, 120, 81, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(predictor)
        self.label_8.setGeometry(QtCore.QRect(880, 120, 81, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(predictor)
        self.label_9.setGeometry(QtCore.QRect(820, 200, 81, 18))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(predictor)
        self.label_10.setGeometry(QtCore.QRect(820, 280, 81, 18))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(predictor)
        self.label_11.setGeometry(QtCore.QRect(20, 700, 150, 61))
        self.label_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_11.setObjectName("label_11")
        self.pushButton_2 = QtWidgets.QPushButton(predictor)
        self.pushButton_2.setGeometry(QtCore.QRect(740, 720, 261, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_12 = QtWidgets.QLabel(predictor)
        self.label_12.setGeometry(QtCore.QRect(190, 520, 451, 51))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(predictor)
        self.label_13.setGeometry(QtCore.QRect(190, 610, 451, 51))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(predictor)
        self.label_14.setGeometry(QtCore.QRect(190, 700, 451, 51))
        self.label_14.setObjectName("label_14")
        self.pushButton = QtWidgets.QPushButton(predictor)
        self.pushButton.setGeometry(QtCore.QRect(810, 680, 112, 34))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(predictor)
        QtCore.QMetaObject.connectSlotsByName(predictor)

    def retranslateUi(self, predictor):
        _translate = QtCore.QCoreApplication.translate
        predictor.setWindowTitle(_translate("predictor", "Dialog"))
        self.label.setText(_translate("predictor", "TextLabel"))
        self.label_2.setText(_translate("predictor", "TextLabel"))
        self.label_3.setText(_translate("predictor", "TextLabel"))
        self.label_4.setText(_translate("predictor", "TextLabel"))
        self.label_5.setText(_translate("predictor", "TextLabel"))
        self.label_6.setText(_translate("predictor", "TextLabel"))
        self.label_7.setText(_translate("predictor", "TextLabel"))
        self.label_8.setText(_translate("predictor", "TextLabel"))
        self.label_9.setText(_translate("predictor", "TextLabel"))
        self.label_10.setText(_translate("predictor", "TextLabel"))
        self.label_11.setText(_translate("predictor", "TextLabel"))
        self.pushButton_2.setText(_translate("predictor", "妆容推荐"))
        self.label_12.setText(_translate("predictor", "TextLabel"))
        self.label_13.setText(_translate("predictor", "TextLabel"))
        self.label_14.setText(_translate("predictor", "TextLabel"))
        self.pushButton.setText(_translate("predictor", "PushButton"))

